name: Sencha Cmd
description: A GitHub Action wrapping Sencha Cmd

inputs:
  dir:
    description: 'Root directory for ExtJS application'
    required: true
    default: './web'
  cmd:
    description: 'Command to run'
    required: true
    default: 'app build'

runs:
  using: docker
  image: docker://rockmagicnet/sencha-cmd:6.2.2
  entrypoint: '/bin/sh -c'
  args:
    - 'cd ${{ inputs.dir }}'
    - 'sencha ${{ inputs.cmd }}'